# Generated by Django 4.2.7 on 2023-12-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pre_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="week_of_pregnancy",
            field=models.IntegerField(null=True),
        ),
    ]
