# Generated by Django 4.2.7 on 2023-12-25 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pregnancy",
            "0003_userprofile_current_weight_userprofile_pre_weight_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="week_update_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
