# Generated by Django 4.2.7 on 2023-12-25 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0004_userprofile_week_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="week_update_date",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
