# Generated by Django 4.2.7 on 2023-12-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0008_test_usertest"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="UserTest",
        ),
    ]
