# Generated by Django 4.2.7 on 2023-12-26 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0009_test_done_delete_usertest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="currentWeight_update_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
