# Generated by Django 4.2.7 on 2023-12-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0010_userprofile_currentweight_update_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="week",
            new_name="trimester",
        ),
        migrations.RemoveField(
            model_name="test",
            name="done",
        ),
        migrations.AddField(
            model_name="test",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
