# Generated by Django 4.2.7 on 2023-12-27 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0014_alter_test_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="user",
        ),
    ]
