# Generated by Django 4.2.7 on 2023-12-27 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0015_remove_test_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
