# Generated by Django 4.2.7 on 2023-12-27 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0017_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="user",
        ),
        migrations.AddField(
            model_name="test",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="test_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
