# Generated by Django 4.2.7 on 2023-12-27 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0018_remove_test_user_test_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="users",
        ),
        migrations.AddField(
            model_name="test",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
