# Generated by Django 4.2.7 on 2023-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0019_remove_test_users_test_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tests",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="users", to="pregnancy.test"
            ),
        ),
    ]
