# Generated by Django 4.2.7 on 2023-12-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0020_remove_test_user_userprofile_tests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="tests",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="usertests", to="pregnancy.test"
            ),
        ),
    ]
