# Generated by Django 4.2.7 on 2023-12-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0021_alter_userprofile_tests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="done",
            field=models.BooleanField(),
        ),
    ]
