# Generated by Django 4.2.7 on 2023-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pregnancy", "0022_alter_test_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="counselling_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="diet_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="test",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
